### ISSUE TITLE
Error running on DNN 8

### ISSUE THREAD

**Issue by gregclemens** [roman-yagodin/R7.DotNetNuke.Extensions#5]
Roman,
Hello.  I just installed the latest version of your R7 module.  I'm getting an error message. I'm running dnn 8.0.1.

![screen shot 2016-07-12 at 2 03 46 pm](https://cloud.githubusercontent.com/assets/8192944/16777981/e492ea98-4839-11e6-9abf-92a05f932107.png)

**Comment by roman-yagodin** [comment]
The R7.DotNetNuke.Extensions library (and all modules based on it) currently targets DNN 7.4.2 - which is currently a base for all my production environments. There are some breaking changes in DNN 8, which makes many third-party extensions incompatible. I'm sorry, but currently I cannot provide support for two different versions of R7.DotNetNuke.Extensions library nor any module based on it.

Just wondering, which module you try to install?

**Comment by gregclemens** [comment]
It was your Documents module.

I'm just looking for a simple way for users to download a .pdf.  Any
suggestions?  Initially I was looking to send an automated email with an
attachment in it after they filled out a form.  I couldn't find a simple
way to do that in DNN so I settled for this solution.  Thanks.

On Wed, Jul 13, 2016 at 1:34 AM, Roman M. Yagodin <notifications@github.com>
wrote:

> The R7.DotNetNuke.Extensions library (and all modules based on it)
> currently targets DNN 7.4.2 - which is currently a base for all my
> production environments. There are some breaking changes in DNN 8, which
> makes many third-party extensions incompatible. I'm sorry, but currently I
> cannot provide support for two different versions of
> R7.DotNetNuke.Extensions library nor any module based on it.
>
> Just wondering, which module you try to install?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/roman-yagodin/R7.DotNetNuke.Extensions/issues/5#issuecomment-232260669>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AH0DsB1HrHdx_2yFUoaqna03bypZVYGpks5qVHjsgaJpZM4JKqdb>
> .
>



-- 

*Greg*

*Greg Clemens*
SentOnesNetwork.org
Global Service Network <http://www.globalservicenet.org/giving/51013007>
cell: 404.771.5032

<http://sentonesnetwork.org/>
<https://www.facebook.com/Greg-Sarah-Clemens-Kingdom-Mobilization-233186136740944/>
   <https://twitter.com/GregoryClemens>
<https://www.gcx.org/GregandSarahClemens/>

**Comment by roman-yagodin** [comment]
I think this should be solved by R7.DotNetNuke.Extensions v0.9.0 and R7.Documents v1.8.1 releases.
